[[bin]]
name = "util"
path = "src/util/util.rs"

[[bin]]
name = "2023-01"
path = 'src\solutions\2023\day-01.rs'

[[bin]]
name = "2023-02"
path = 'src\solutions\2023\day-02.rs'

[[bin]]
name = "2023-03"
path = 'src\solutions\2023\day-03.rs'

[[bin]]
name = "2023-04"
path = 'src\solutions\2023\day-04.rs'

[[bin]]
name = "2023-05"
path = 'src\solutions\2023\day-05.rs'

[dependencies]
chrono = "0.4.31"
nom = "7.1.3"
toml = "0.8.8"

[dependencies.clap]
features = ["derive"]
version = "4.4.11"

[package]
edition = "2021"
name = "aoc-rust"
version = "0.1.0"
