name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up rust
        uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --verbose --all-targets --all-features -- -D warnings